/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace LiquidityPoolFactory {
  export type PoolInfoStruct = {
    poolAddress: AddressLike;
    memecoinAddress: AddressLike;
    creator: AddressLike;
    memecoinReserve: BigNumberish;
    airReserve: BigNumberish;
    lpTokensBurned: BigNumberish;
    createdAt: BigNumberish;
    lpTokensBurnedFlag: boolean;
  };

  export type PoolInfoStructOutput = [
    poolAddress: string,
    memecoinAddress: string,
    creator: string,
    memecoinReserve: bigint,
    airReserve: bigint,
    lpTokensBurned: bigint,
    createdAt: bigint,
    lpTokensBurnedFlag: boolean
  ] & {
    poolAddress: string;
    memecoinAddress: string;
    creator: string;
    memecoinReserve: bigint;
    airReserve: bigint;
    lpTokensBurned: bigint;
    createdAt: bigint;
    lpTokensBurnedFlag: boolean;
  };
}

export interface LiquidityPoolFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BURN_ADDRESS"
      | "GRADUATION_THRESHOLD"
      | "airToken"
      | "allPools"
      | "areLPTokensBurned"
      | "burnLPTokens"
      | "checkGraduationEligibility"
      | "createLiquidityPool"
      | "getPoolByMemecoin"
      | "getPoolInfo"
      | "getTotalPools"
      | "memecoinToPool"
      | "owner"
      | "poolInfo"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GraduationThresholdChecked"
      | "LPTokensBurned"
      | "OwnershipTransferred"
      | "PoolCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BURN_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRADUATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "airToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "areLPTokensBurned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLPTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkGraduationEligibility",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLiquidityPool",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolByMemecoin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memecoinToPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BURN_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRADUATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "airToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "areLPTokensBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnLPTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkGraduationEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLiquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolByMemecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memecoinToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace GraduationThresholdCheckedEvent {
  export type InputTuple = [
    memecoinAddress: AddressLike,
    marketCap: BigNumberish,
    eligible: boolean
  ];
  export type OutputTuple = [
    memecoinAddress: string,
    marketCap: bigint,
    eligible: boolean
  ];
  export interface OutputObject {
    memecoinAddress: string;
    marketCap: bigint;
    eligible: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensBurnedEvent {
  export type InputTuple = [
    poolAddress: AddressLike,
    memecoinAddress: AddressLike,
    lpTokensBurned: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolAddress: string,
    memecoinAddress: string,
    lpTokensBurned: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolAddress: string;
    memecoinAddress: string;
    lpTokensBurned: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolAddress: AddressLike,
    memecoinAddress: AddressLike,
    creator: AddressLike,
    memecoinReserve: BigNumberish,
    airReserve: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolAddress: string,
    memecoinAddress: string,
    creator: string,
    memecoinReserve: bigint,
    airReserve: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolAddress: string;
    memecoinAddress: string;
    creator: string;
    memecoinReserve: bigint;
    airReserve: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityPoolFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityPoolFactory;
  waitForDeployment(): Promise<this>;

  interface: LiquidityPoolFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BURN_ADDRESS: TypedContractMethod<[], [string], "view">;

  GRADUATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  airToken: TypedContractMethod<[], [string], "view">;

  allPools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  areLPTokensBurned: TypedContractMethod<
    [poolAddress: AddressLike],
    [boolean],
    "view"
  >;

  burnLPTokens: TypedContractMethod<
    [poolAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  checkGraduationEligibility: TypedContractMethod<
    [
      memecoinAddress: AddressLike,
      currentPrice: BigNumberish,
      tokensSold: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  createLiquidityPool: TypedContractMethod<
    [
      memecoinAddress: AddressLike,
      creator: AddressLike,
      memecoinAmount: BigNumberish,
      airAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getPoolByMemecoin: TypedContractMethod<
    [memecoinAddress: AddressLike],
    [string],
    "view"
  >;

  getPoolInfo: TypedContractMethod<
    [poolAddress: AddressLike],
    [LiquidityPoolFactory.PoolInfoStructOutput],
    "view"
  >;

  getTotalPools: TypedContractMethod<[], [bigint], "view">;

  memecoinToPool: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        poolAddress: string;
        memecoinAddress: string;
        creator: string;
        memecoinReserve: bigint;
        airReserve: bigint;
        lpTokensBurned: bigint;
        createdAt: bigint;
        lpTokensBurnedFlag: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BURN_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRADUATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "airToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allPools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "areLPTokensBurned"
  ): TypedContractMethod<[poolAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "burnLPTokens"
  ): TypedContractMethod<[poolAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkGraduationEligibility"
  ): TypedContractMethod<
    [
      memecoinAddress: AddressLike,
      currentPrice: BigNumberish,
      tokensSold: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createLiquidityPool"
  ): TypedContractMethod<
    [
      memecoinAddress: AddressLike,
      creator: AddressLike,
      memecoinAmount: BigNumberish,
      airAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPoolByMemecoin"
  ): TypedContractMethod<[memecoinAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolAddress: AddressLike],
    [LiquidityPoolFactory.PoolInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPools"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "memecoinToPool"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        poolAddress: string;
        memecoinAddress: string;
        creator: string;
        memecoinReserve: bigint;
        airReserve: bigint;
        lpTokensBurned: bigint;
        createdAt: bigint;
        lpTokensBurnedFlag: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GraduationThresholdChecked"
  ): TypedContractEvent<
    GraduationThresholdCheckedEvent.InputTuple,
    GraduationThresholdCheckedEvent.OutputTuple,
    GraduationThresholdCheckedEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensBurned"
  ): TypedContractEvent<
    LPTokensBurnedEvent.InputTuple,
    LPTokensBurnedEvent.OutputTuple,
    LPTokensBurnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;

  filters: {
    "GraduationThresholdChecked(address,uint256,bool)": TypedContractEvent<
      GraduationThresholdCheckedEvent.InputTuple,
      GraduationThresholdCheckedEvent.OutputTuple,
      GraduationThresholdCheckedEvent.OutputObject
    >;
    GraduationThresholdChecked: TypedContractEvent<
      GraduationThresholdCheckedEvent.InputTuple,
      GraduationThresholdCheckedEvent.OutputTuple,
      GraduationThresholdCheckedEvent.OutputObject
    >;

    "LPTokensBurned(address,address,uint256,uint256)": TypedContractEvent<
      LPTokensBurnedEvent.InputTuple,
      LPTokensBurnedEvent.OutputTuple,
      LPTokensBurnedEvent.OutputObject
    >;
    LPTokensBurned: TypedContractEvent<
      LPTokensBurnedEvent.InputTuple,
      LPTokensBurnedEvent.OutputTuple,
      LPTokensBurnedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolCreated(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
  };
}
