/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MemecoinFactory {
  export type MemecoinDeploymentStruct = {
    memecoinAddress: AddressLike;
    bondingCurveAddress: AddressLike;
    creator: AddressLike;
    symbol: string;
    deployedAt: BigNumberish;
  };

  export type MemecoinDeploymentStructOutput = [
    memecoinAddress: string,
    bondingCurveAddress: string,
    creator: string,
    symbol: string,
    deployedAt: bigint
  ] & {
    memecoinAddress: string;
    bondingCurveAddress: string;
    creator: string;
    symbol: string;
    deployedAt: bigint;
  };
}

export interface MemecoinFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BONDING_CURVE_K"
      | "BONDING_CURVE_SUPPLY"
      | "allMemecoins"
      | "createMemecoin"
      | "creatorMemecoins"
      | "getCreatorMemecoins"
      | "getMemecoinBySymbol"
      | "getTotalMemecoins"
      | "owner"
      | "platformWallet"
      | "renounceOwnership"
      | "symbolToMemecoin"
      | "transferOwnership"
      | "updatePlatformWallet"
      | "usdcAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemecoinCreated"
      | "OwnershipTransferred"
      | "PlatformWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BONDING_CURVE_K",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BONDING_CURVE_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allMemecoins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMemecoin",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorMemecoins",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorMemecoins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemecoinBySymbol",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMemecoins",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "symbolToMemecoin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usdcAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BONDING_CURVE_K",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BONDING_CURVE_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allMemecoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMemecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorMemecoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorMemecoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemecoinBySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMemecoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "symbolToMemecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdcAddress",
    data: BytesLike
  ): Result;
}

export namespace MemecoinCreatedEvent {
  export type InputTuple = [
    memecoinAddress: AddressLike,
    bondingCurveAddress: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    bondingCurveSupply: BigNumberish
  ];
  export type OutputTuple = [
    memecoinAddress: string,
    bondingCurveAddress: string,
    creator: string,
    name: string,
    symbol: string,
    totalSupply: bigint,
    bondingCurveSupply: bigint
  ];
  export interface OutputObject {
    memecoinAddress: string;
    bondingCurveAddress: string;
    creator: string;
    name: string;
    symbol: string;
    totalSupply: bigint;
    bondingCurveSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemecoinFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MemecoinFactory;
  waitForDeployment(): Promise<this>;

  interface: MemecoinFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BONDING_CURVE_K: TypedContractMethod<[], [bigint], "view">;

  BONDING_CURVE_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  allMemecoins: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
        creator: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;

  createMemecoin: TypedContractMethod<
    [name: string, symbol: string, creator: AddressLike],
    [
      [string, string] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
      }
    ],
    "nonpayable"
  >;

  creatorMemecoins: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
        creator: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;

  getCreatorMemecoins: TypedContractMethod<
    [creator: AddressLike],
    [MemecoinFactory.MemecoinDeploymentStructOutput[]],
    "view"
  >;

  getMemecoinBySymbol: TypedContractMethod<[symbol: string], [string], "view">;

  getTotalMemecoins: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  symbolToMemecoin: TypedContractMethod<[arg0: string], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformWallet: TypedContractMethod<
    [newPlatformWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BONDING_CURVE_K"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BONDING_CURVE_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allMemecoins"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
        creator: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createMemecoin"
  ): TypedContractMethod<
    [name: string, symbol: string, creator: AddressLike],
    [
      [string, string] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorMemecoins"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        memecoinAddress: string;
        bondingCurveAddress: string;
        creator: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorMemecoins"
  ): TypedContractMethod<
    [creator: AddressLike],
    [MemecoinFactory.MemecoinDeploymentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemecoinBySymbol"
  ): TypedContractMethod<[symbol: string], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalMemecoins"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbolToMemecoin"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformWallet"
  ): TypedContractMethod<
    [newPlatformWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MemecoinCreated"
  ): TypedContractEvent<
    MemecoinCreatedEvent.InputTuple,
    MemecoinCreatedEvent.OutputTuple,
    MemecoinCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformWalletUpdated"
  ): TypedContractEvent<
    PlatformWalletUpdatedEvent.InputTuple,
    PlatformWalletUpdatedEvent.OutputTuple,
    PlatformWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "MemecoinCreated(address,address,address,string,string,uint256,uint256)": TypedContractEvent<
      MemecoinCreatedEvent.InputTuple,
      MemecoinCreatedEvent.OutputTuple,
      MemecoinCreatedEvent.OutputObject
    >;
    MemecoinCreated: TypedContractEvent<
      MemecoinCreatedEvent.InputTuple,
      MemecoinCreatedEvent.OutputTuple,
      MemecoinCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformWalletUpdated(address,address)": TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
    PlatformWalletUpdated: TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
  };
}
